#name: Paper-Test-Plugin
#version: ${version}
##main: io.papermc.testplugin.TestPlugin
#main: org.obsidian.testplugin.TestPlugin
#description: Paper Test Plugin
#author: PaperMC
#api-version: ${apiversion}
#load: STARTUP
##bootstrapper: io.papermc.testplugin.TestPluginBootstrap
##loader: io.papermc.testplugin.TestPluginLoader
#defaultPerm: FALSE
#commands:
#  test:
#permissions:
#dependencies:

main: org.obsidian.testplugin.TestPlugin
api-version: '1.21'

name: ObsidianPlugin
version: 0.0.1
author: dani33y
description: Test plugin

commands:
  test:
    description: "Comando de prueba"
    usage: "/test"

